# Generated by Django 6.0.5 on 2026-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
