# Generated by Django 6.0.5 on 2026-07-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountdetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('shop_owner', 'Shop Owner')], default='shop_owner', max_length=50),
        ),
    ]
